### ISSUE TITLE
[Android] App crashes:  java.lang.NoSuchMethodError: No static method koinApplication(Lkotlin/jvm/functions/Function1;)

### ISSUE THREAD

**Issue by ilyagru** [Driversnote-Dev/react-native-helpscout-beacon#21]
If I add this library, the app crashes on launch. Everything is fine on iOS.

It might be related to https://github.com/expo/expo/issues/29047.

```
FATAL EXCEPTION: main
  Process: app, PID: 25877
  java.lang.NoSuchMethodError: No static method koinApplication(Lkotlin/jvm/functions/Function1;)Lorg/koin/core/KoinApplication; in class Lorg/koin/dsl/KoinApplicationKt; or its super classes (declaration of 'org.koin.dsl.KoinApplicationKt' appears in /data/app/~~JbxgbEkaPG8LrM5YBSjiIA==/app-eptDv5N7AIY6ymGpqln4-w==/base.apk!classes8.dex)
  	at expo.modules.devlauncher.koin.DevLauncherKoinAppKt$koinAppFactory$1.invoke(DevLauncherKoinApp.kt:29)
  	at expo.modules.devlauncher.koin.DevLauncherKoinAppKt$koinAppFactory$1.invoke(DevLauncherKoinApp.kt:28)
  	at expo.modules.devlauncher.koin.DevLauncherKoinContext.<clinit>(DevLauncherKoinApp.kt:35)
  	at expo.modules.devlauncher.DevLauncherController$Companion.wasInitialized(DevLauncherController.kt:382)
  	at expo.modules.devlauncher.launcher.DevLauncherReactNativeHostHandler.getUseDeveloperSupport(DevLauncherReactNativeHostHandler.kt:22)
  	at expo.modules.ReactNativeHostWrapperBase$getUseDeveloperSupport$1.invoke(ReactNativeHostWrapperBase.kt:72)
  	at expo.modules.ReactNativeHostWrapperBase$getUseDeveloperSupport$1.invoke(ReactNativeHostWrapperBase.kt:72)
  	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
  	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
  	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
  	at kotlin.sequences.SequencesKt___SequencesKt.firstOrNull(_Sequences.kt:168)
  	at expo.modules.ReactNativeHostWrapperBase.getUseDeveloperSupport(ReactNativeHostWrapperBase.kt:73)
  	at expo.modules.ExpoReactHostFactory.createFromReactNativeHost(ExpoReactHostFactory.kt:93)
  	at expo.modules.ReactNativeHostWrapper$Companion.createReactHost(ReactNativeHostWrapper.kt:53)
  	at app.MainApplication.getReactHost(MainApplication.kt:39)
  	at expo.modules.devlauncher.DevLauncherController$Companion.initialize(DevLauncherController.kt:430)
  	at expo.modules.devlauncher.DevLauncherController$Companion.initialize$default(DevLauncherController.kt:429)
  	at expo.modules.devlauncher.DevLauncherPackageDelegate$createApplicationLifecycleListeners$1.onCreate(DevLauncherPackageDelegate.kt:38)
  	at expo.modules.ApplicationLifecycleDispatcher.onApplicationCreate(ApplicationLifecycleDispatcher.kt:20)
  	at app.MainApplication.onCreate(MainApplication.kt:48)
  	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1316)
  	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6998)
  	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
  	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2236)
  	at android.os.Handler.dispatchMessage(Handler.java:106)
  	at android.os.Looper.loopOnce(Looper.java:205)
  	at android.os.Looper.loop(Looper.java:294)
  	at android.app.ActivityThread.main(ActivityThread.java:8177)
  	at java.lang.reflect.Method.invoke(Native Method)
  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

### Versions

```
    "expo": "~51.0.34",
    "expo-dev-client": "~4.0.29",
    "react-native": "0.74.5",
    "react-native-helpscout-beacon": "^0.6.0",
```

**Comment by ilyagru** [comment]
Forcing koin:3.5.6 doesn't help

https://slack-chats.kotlinlang.org/t/16047047/hello-guys-i-m-trying-to-update-koin-from-3-3-0-to-3-5-0-in-

**Comment by steveliles** [comment]
I'm trying to upgrade from expo 50 -> 51 and seeing this same issue on Android only. 

On Expo 50 both platforms were fine.

My iOS app is running with expo 51, and helpscout is working there. 

hacking around in a fork of this lib I've found that:
- staying on helpscout 5.0.2 causes build problems due to Error resolving plugin [id: 'com.facebook.react.settings']
- upgrading to helpscout 5.1.2 causes build problems due to Error resolving plugin [id: 'com.facebook.react.settings']
- upgrading to helpscout 5.2.1 causes runtime crash described by the OP (No static method koinApplication...)
- upgrading to helpscout 6.0.1 causes build problems due to incompatible kotlin versions

I don't really know where to go from here ... any suggestions would be much appreciated!

**Comment by diegocouto** [comment]
Hi @steveliles, did you manage to find a solution for your case? I'm now having the same headache. 😅 

**Update:** I managed to overcome this issue but patching the `expo-dev-launcher` [as described here](https://github.com/argyle-systems/argyle-link-react-native/issues/134#issuecomment-2501414020).
